# Generated by Django 4.2.2 on 2023-06-26 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='game',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_comments', to='games.company', verbose_name='компания'),
        ),
        migrations.AddField(
            model_name='comment',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_comments', to='games.game', verbose_name='игра'),
        ),
        migrations.AlterField(
            model_name='game',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_games', to='games.company', verbose_name='компания'),
        ),
    ]
