# Generated by Django 4.2.2 on 2023-07-04 13:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0002_remove_company_comments_remove_game_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-id',), 'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('-datetime_created',), 'verbose_name': 'компания', 'verbose_name_plural': 'компании'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('price', 'name'), 'verbose_name': 'игра', 'verbose_name_plural': 'игры'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',), 'verbose_name': 'жанр', 'verbose_name_plural': 'жанры'},
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games', models.ManyToManyField(related_name='wishlists', to='games.game', verbose_name='игра')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='властелин')),
            ],
            options={
                'verbose_name': 'избранный',
                'verbose_name_plural': 'избранные',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_buy', models.DateTimeField(auto_now_add=True, verbose_name='время совершения покупки')),
                ('method', models.CharField(choices=[('0', 'карта'), ('1', 'наличкой при доставке')], default='0', max_length=250, verbose_name='метод оплаты')),
                ('money', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='потрачено')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='games.game', verbose_name='игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, verbose_name='юзер')),
            ],
            options={
                'verbose_name': 'покупка',
                'verbose_name_plural': 'покупки',
            },
        ),
        migrations.CreateModel(
            name='InviteCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='код')),
                ('expiration_date', models.DateField(default=datetime.datetime(2023, 8, 3, 19, 37, 8, 795139), verbose_name='дата истечения')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='счётчик')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
            ],
            options={
                'verbose_name': 'пригласительная карта',
                'verbose_name_plural': 'пригласительные карты',
                'ordering': ('-counter',),
            },
        ),
    ]
