# Generated by Django 4.2.3 on 2023-07-07 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_comment_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 6, 19, 24, 52, 102035), verbose_name='дата истечения'),
        ),
    ]
