# Generated by Django 4.2.2 on 2023-07-21 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_invitecard_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='imgor',
            field=models.ImageField(default='games/unknown.png', upload_to='games/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 20, 18, 57, 21, 199102), verbose_name='дата истечения'),
        ),
    ]
