# Generated by Django 4.2.2 on 2023-07-21 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_imgor_alter_invitecard_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='imgor',
            new_name='main_imgor',
        ),
        migrations.AlterField(
            model_name='invitecard',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 20, 19, 27, 32, 725678), verbose_name='дата истечения'),
        ),
    ]
